# Generated by Django 4.2.2 on 2023-07-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('hora', models.TimeField()),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('nombre_dueno', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
