# Generated by Django 4.2.2 on 2023-07-05 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaMiMascota', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='completada',
        ),
        migrations.AddField(
            model_name='cita',
            name='hora_texto',
            field=models.CharField(default='09:00', max_length=5),
            preserve_default=False,
        ),
    ]
