# Generated by Django 4.2.2 on 2023-07-11 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('veterinariaMiMascota', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='veterinariaMiMascota.userprofile'),
        ),
    ]
